# Generated by Django 5.0.4 on 2024-05-22 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction_zsmart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('compte', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('statut_compte', models.CharField(max_length=100, null=True)),
                ('date_creation', models.DateTimeField()),
                ('verrouille', models.CharField(max_length=20, null=True)),
                ('profil', models.CharField(max_length=20, null=True)),
                ('commentaire', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Extraction_zsmart',
                'verbose_name_plural': 'Extraction_zsmarts',
            },
        ),
    ]
