# Generated by Django 5.0.4 on 2024-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_zsmart',
            name='date_creation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
