# Generated by Django 5.0.4 on 2024-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zsmart', '0002_alter_extraction_zsmart_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_zsmart',
            name='profil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_zsmart',
            name='verrouille',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
