# Generated by Django 5.0.4 on 2024-05-27 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction_ams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('full_user_name', models.CharField(max_length=100, null=True)),
                ('email_address', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('change_password', models.CharField(max_length=100, null=True)),
                ('bypass_password', models.CharField(max_length=100, null=True)),
                ('roles', models.CharField(max_length=100, null=True)),
                ('allowed_pap_group', models.CharField(max_length=100, null=True)),
                ('use_global_max_number_of_concurrent_sessions', models.CharField(max_length=100, null=True)),
                ('locked', models.CharField(max_length=100, null=True)),
                ('commentaire', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Extraction_ams',
                'verbose_name_plural': 'Extraction_ams',
            },
        ),
    ]
