# Generated by Django 5.0.4 on 2024-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_zoom',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
