# Generated by Django 5.0.4 on 2024-06-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_alter_extraction_zoom_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_zoom',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
