# Generated by Django 5.0.4 on 2024-05-13 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction_ussd_osn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('User', models.CharField(max_length=75, unique=True)),
                ('Group', models.CharField(max_length=500)),
                ('commentaire', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Extraction_ussd_osn',
                'verbose_name_plural': 'Extraction_ussd_osns',
            },
        ),
    ]
