# Generated by Django 5.0.4 on 2024-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretups',
            name='commentaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='last_login_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='msisdn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='traitement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
