# Generated by Django 5.0.4 on 2024-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0002_alter_pretups_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretups',
            name='last_login_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='login_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='msisdn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pretups',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
