# Generated by Django 5.0.4 on 2024-05-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0003_alter_pretups_last_login_on_alter_pretups_login_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pretups',
            options={'verbose_name': 'Pretups', 'verbose_name_plural': 'Pretupss'},
        ),
    ]
