# Generated by Django 5.0.4 on 2024-05-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0004_alter_pretups_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pretups',
            name='last_login_on',
        ),
    ]
