# Generated by Django 5.0.4 on 2024-05-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0005_remove_pretups_last_login_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pretups',
            new_name='Extraction_pretups',
        ),
    ]
