# Generated by Django 5.0.4 on 2024-05-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0006_rename_pretups_extraction_pretups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraction_pretups',
            options={'verbose_name': 'Extraction_pretups', 'verbose_name_plural': 'Extraction_pretupss'},
        ),
    ]
