# Generated by Django 5.0.4 on 2024-05-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0007_alter_extraction_pretups_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction_pretups',
            name='last_login_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
