# Generated by Django 5.0.4 on 2024-05-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0009_alter_extraction_pretups_last_login_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_pretups',
            name='last_login_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
