# Generated by Django 5.0.4 on 2024-06-11 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0011_alter_extraction_pretups_last_login_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction_pretups',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='employee_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='group_role_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='parent_msisdn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='parent_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='role_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='role_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extraction_pretups',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_pretups',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='extraction_pretups',
            name='last_login_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
