# Generated by Django 5.0.4 on 2024-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0012_extraction_pretups_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_pretups',
            name='login_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
