# Generated by Django 5.0.4 on 2024-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0013_alter_extraction_pretups_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_pretups',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_pretups',
            name='last_login_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_pretups',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
