# Generated by Django 5.0.4 on 2024-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretups', '0015_extraction_pretups_last_login_on_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_pretups',
            name='created_on',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_pretups',
            name='modified_on',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
