# Generated by Django 5.0.4 on 2024-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_nac',
            name='Description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_nac',
            name='Locale',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_nac',
            name='Name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_nac',
            name='Password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_nac',
            name='Profile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_nac',
            name='UserType',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
