# Generated by Django 5.0.4 on 2024-05-09 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction_naf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Profile', models.CharField(max_length=50)),
                ('Locale', models.CharField(max_length=50)),
                ('UserType', models.CharField(max_length=50)),
                ('PasswordUpdateDate', models.DateTimeField(blank=True, null=True)),
                ('Attempts', models.DateTimeField(blank=True, null=True)),
                ('AccountLocked', models.DateTimeField(blank=True, null=True)),
                ('LockedTime', models.DateTimeField(blank=True, null=True)),
                ('isFirstPasswordChanged', models.DateTimeField(blank=True, null=True)),
                ('MailAddress', models.CharField(max_length=200, null=True)),
                ('Description', models.DateTimeField(blank=True, null=True)),
                ('EmailNotification', models.CharField(max_length=200, null=True)),
                ('commentaire', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Extraction_naf',
                'verbose_name_plural': 'Extraction_nafs',
            },
        ),
    ]
