# Generated by Django 5.0.4 on 2024-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_naf',
            name='AccountLocked',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_naf',
            name='Attempts',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_naf',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_naf',
            name='isFirstPasswordChanged',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
