# Generated by Django 5.0.4 on 2024-05-21 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe_AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('sam_account_name', models.CharField(max_length=100, null=True)),
                ('email_address', models.CharField(max_length=100, null=True)),
                ('account_status', models.CharField(max_length=100, null=True)),
                ('commentaire', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Groupe_AD',
                'verbose_name_plural': 'Groupe_ADs',
            },
        ),
    ]
